import RIDE_SCREENS from "./Rides/Screens";
import PROFILE_SCREENS from "./Profile/Screens";

enum TAB_SCREENS {
  NOTIFICATIONS_TAB = 'NOTIFICATIONS_TAB',
  PROFILE_TAB = 'PROFILE_TAB',
  SETTINGS_TAB = 'SETTINGS_TAB',
  RIDES_TAB = 'RIDES_TAB',
  CREATE_RIDE_TAB = 'CREATE_RIDE_TAB'
}

export default { ...TAB_SCREENS, ...RIDE_SCREENS, ...PROFILE_SCREENS };
