enum Screens {
  LIFT = 'LIFT',
  RIDE = 'RIDE',
  REVIEW = 'REVIEW',
  USER_PROFILE = 'USER_PROFILE',
  RIDE_DETAILS = 'RIDE_DETAILS',
  RIDEREQUEST_DETAILS = 'RIDEREQUEST_DETAILS',
  PASSENGER_DETAILS = 'PASSENGER_DETAILS'
}

export default Screens;
