enum Screens {
  RIDE = 'RIDE',
  REVIEW = 'REVIEW',
  USER_PROFILE = 'USER_PROFILE',
  RIDE_DETAILS = 'RIDE_DETAILS',
  WHERE_FROM_WHERE_TO_DETAILS = 'WHERE_FROM_WHERE_TO_DETAILS',
  WELCOME = 'WELCOME',
  JOIN_RIDE = 'JOIN_RIDE',
  SEARCH_FOR_RIDE = 'SEARCH_FOR_RIDE'
}

export default Screens;
